### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/podium-api#15]
These need to be fixed:

```
...........................................................................................................................................................E..........................................................................................
 ======================================================================
 ERROR: test_friendships_get (tests.test_friendships.TestFriendshipsGet)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/brent/.pyenv/versions/3.8.9/envs/podium-api/lib/python3.8/site-packages/mock/mock.py", line 1305, in patched
     return func(*args, **keywargs)
   File "/home/brent/git-projects/podium-api/tests/test_friendships.py", line 291, in test_friendships_get
     req.on_success()(req, self.paged_event_json)
   File "/home/brent/git-projects/podium-api/podium_api/asyncreq.py", line 127, in <lambda>
     on_success=(lambda req, res: on_success(req, res, data)) if on_success is not None else None,
   File "/home/brent/git-projects/podium-api/podium_api/friendships.py", line 353, in friendships_success_handler
     data["success_callback"](get_paged_response_from_json(results, "users"))
   File "/home/brent/git-projects/podium-api/podium_api/types/paged_response.py", line 75, in get_paged_response_from_json
     data = [conversion_func(x) for x in json[payload_name]]
   File "/home/brent/git-projects/podium-api/podium_api/types/paged_response.py", line 75, in <listcomp>
     data = [conversion_func(x) for x in json[payload_name]]
   File "/home/brent/git-projects/podium-api/podium_api/types/user.py", line 87, in get_user_from_json
     json["name"],
 KeyError: 'name'
```

**Comment by brentpicasso** [comment]
fixed in 0.1.0
